### ISSUE TITLE
Add Fit tool within standalone list

### ISSUE THREAD

**Issue by vxsh4d0w** [digitalsleuth/winfor-salt#12]
Please consider adding this tool for forensic acquisition of contents like web pages, emails, social media, etc.: https://github.com/fit-project/fit,

**Comment by digitalsleuth** [comment]
Looks like a good tool! I'll start testing it now. Cheers!

**Comment by digitalsleuth** [comment]
FIT has been added, and is available under Acquisition and Analysis. Cheers!
