### ISSUE TITLE
[FQ] - Move Portals Shortcut to Public Desktop when Unchecked

### ISSUE THREAD

**Issue by angry-bender** [digitalsleuth/winfor-salt#18]
Hey mate,

Just had an idea for a feature request. Where portals is unchecked, would it be possible to place the same shortcut files in C:\Users\public\desktop That makes the folders for tools easily discoverable without needing portals.

**Comment by digitalsleuth** [comment]
Hey @angry-bender , this is a good idea. I'll set up a new state file to do just that. Cheers!

**Comment by digitalsleuth** [comment]
Hi @angry-bender , with release 2023.29.0, I've added a new state file which will check for the existence of Portals and, if not installed, will create the desktop shortcuts for each folder, which would originally have been the source for the assigned Portal, and will create that folder on the Public Desktop.

Thanks for the idea!

**Comment by angry-bender** [comment]
Thanks au much, this will save me doing this manually 😊
