### ISSUE TITLE
fec 4.0.200.

### ISSUE THREAD

**Issue by dursun0007** [digitalsleuth/winfor-salt#26]
[4.0.200.1093](https://fec.metaspike.com/announcements/402001093)
FEC Release
🔥Major improvements to Gmail API throttling mitigation.

✔️Added protection to prevent multiple computers from operating on the same FEC project simultaneously.

✔️Other performance and user interface improvements.

**Comment by digitalsleuth** [comment]
Hi @dursun0007 , this has been updated in release v2024.15.2. Cheers!

**Comment by dursun0007** [comment]
18 Oct, 2024
[4.0.231.1071](https://fec.metaspike.com/announcements/402311071)
FEC Release
This is a maintenance release with the following improvement:

✔️Drive Explorer cache is now invalidated if the list of selected Google Drives is changed on FEC's tree view.
