### ISSUE TITLE
FEI v2.2

### ISSUE THREAD

**Issue by dursun0007** [digitalsleuth/winfor-salt#27]
trial download link

**Comment by digitalsleuth** [comment]
Good afternoon @dursun0007 , I don't see a download link in your message. Did you intend to add one, or were you asking for one?

**Comment by dursun0007** [comment]
FEI v2.2

**Comment by dursun0007** [comment]
Do you have the FEI v2.2 download link? If so, can you update or add it?

**Comment by digitalsleuth** [comment]
No, I don't have a link to the trial. I think that might be something you have to sign-up for. I'll reach out to metaspike and see if I can get one.

**Comment by dursun0007** [comment]
18 Oct, 2024
[4.0.231.1071](https://fec.metaspike.com/announcements/402311071)
FEC Release
This is a maintenance release with the following improvement:

✔️Drive Explorer cache is now invalidated if the list of selected Google Drives is changed on FEC's tree view.

**Comment by digitalsleuth** [comment]
Hi @dursun0007 , this has been updated. For the time being, please add any new issues, tool requests, or updates to a new issue, so I can track this one specifically for FEI.

Cheers

**Comment by digitalsleuth** [comment]
Unfortunately there is no trial option available for FEI from what I've seen, so I'm unable to get a link for this. We can revive this issue in the future if one becomes available.

Cheers
