### ISSUE TITLE
FEC 4.0.238.274

### ISSUE THREAD

**Issue by dursun0007** [digitalsleuth/winfor-salt#28]
Can you add the new update link?

**Comment by digitalsleuth** [comment]
Hi @dursun0007, This has been updated. Also, I get the emails for the updated versions when they're released, and I usually update them within 24-48 hours. With this, you won't have to open a new issue when a new version is released, I'll make sure to get it updated. 

Thanks for the assist!

**Comment by dursun0007** [comment]
OK. thank you

**Comment by dursun0007** [comment]
[4.0.251.1164](https://fec.metaspike.com/announcements/402511164)
FEC Release
✔️Improved progress reporting for Drive acquisitions.

✔️Better handling of Google Drive folder shortcuts during Direct Drive acquisitions.

✔️Minor improvements to Drive acquisition performance.

✔️Other performance and user interface improvements.

**Comment by dursun0007** [comment]
7 Dec, 2024
[4.0.280.1246](https://fec.metaspike.com/announcements/402801246)
✔️Fixed an issue where having both Drive Attachment and Direct Drive acquisition enabled within the same acquisition project could cause unnecessary output duplication.

✔️Further improvements to the handling of Google Drive folder shortcuts during Direct Drive acquisitions.

**Comment by digitalsleuth** [comment]
@dursun0007 this has been updated. For the future, please wait at least 72 hours after the release before raising a new issue or adding to this one. I have a workflow by which these are updated within 24-48 hours after its initial release, so they are regularly maintained. 

Cheers
